### ISSUE TITLE
Audio desync if quest sleeps during rendering

### ISSUE THREAD

**Issue by MrCubicYT** [Metalit/Replay#101]
If your quest goes to sleep whilst rendering, at the point its rendering the audio will skip back a tiny bit and will increase the more times the quest sleeps.

**Comment by MrCubicYT** [comment]
https://www.youtube.com/watch?v=T92IV-D75V8 - Example, wip by TEC_Blenderman
[Rampant.zip](https://github.com/user-attachments/files/17708114/Rampant.zip)

**Comment by MrCubicYT** [comment]
nvm you can choose how long it takes for the quest to sleep bruh

**Comment by christopher317** [comment]
just because there's a workaround doesn't mean it isn't a issue
when rendering with more demanding settings on longer songs it can sometimes take more than 4 hours for a replay to render, so changing the sleep setting is really only putting a band-aid on it.
i have a feeling this issue is related to one i experienced and just submitted.

**Comment by Metalit** [comment]
As I mentioned in the other issue, the next update for 1.37 should prevent the quest from going to sleep while rendering
